[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "geopes"
authors = [{name = "Bart Wolleswinkel", email = "b.wolleswinkel@tudelft.nl"}]
dynamic = ["version", "description"]

[tool.black]
line-length = 120
